language: r
cache: packages
sudo: required
dist: trusty
group: deprecated-2017Q4
warnings_are_errors: false

r_github_packages:
  - jimhester/robustr
  - jimhester/covr
  - hadley/xml2

install:
    - bash ci/install_ckan.sh
services:
    - redis-server
    - postgresql

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - TEST_DPLYR_INTERFACE=TRUE CKANVERSION=2.8
